/*
==============================================
Generated On: 2016-05-19
Generated By: Mike Tellinghuisen
Twitter: @mtellin
Configuring Cisco Switch Orchestrator Workflow
==============================================
----------------------------------------------
==================USAGE=======================
 Workflow for vRealize Orchestrator to leverage
 in vRealize Automation for performing base
 configuration tasks of a Cisco switch via SSH
----------------------------------------------
===============REQUIREMENTS===================
 An attribute with a name of password and type
 Secure String should be created with the
 appropriate password.
----------------------------------------------
*/

session = new SSHSession(hostName, username);
session.connectWithPassword(password);

session.executeCommand("echo `date` >> /tmp/date1.txt", true);
session.executeCommand("echo `date` >> /tmp/date2.txt", true);

session.disconnect();
